language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r lib9ml/python/requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install lib9ml/python --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  nosetests lib9ml/python/test/unit --with-coverage --cover-package=nineml
after_success:
  coveralls
